<?php
header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=greige_keluar".date($_GET['awal']).".xls");//ganti nama sesuai keperluan
header("Pragma: no-cache");
header("Expires: 0");
//disini script laporan anda
?>
<?php
$Awal	= isset($_GET['awal']) ? $_GET['awal'] : '';
$Akhir	= isset($_GET['akhir']) ? $_GET['akhir'] : '';
?>
<?php
ini_set("error_reporting", 1);
include"../../koneksi.php";
//--
//$act=$_POST['act'];
//$tgl=date("Y-m-d");
?>

           <div align="center"> <h1>LAPORAN HARIAN PEMBAGIAN KAIN GREIGE</h1></div>
          <div align="Right"> NO. FORM:<br />
          NO. REVISI:<br />
          TGL Terbit:<br />
          HALAMAN:
          </div>
<div align="LEFT">TGL : <?php echo date($_GET['awal']); ?></div>
<table width="125%" border="1" align="Center">
  <tr align="center">

    <td rowspan="2" >No</td>
    <td rowspan="2" >Tgl Keluar</td>
    <td rowspan="2" >Langganan</td>    
    <td colspan="4" >Jenis Benang</td>
    <td rowspan="2" >Jenis Kain</td>
    <td rowspan="2" >Celup</td>
    <td rowspan="2" >Roll</td>
    <td rowspan="2" >Quantity (KG)</td>
    <td rowspan="2" >Warna</td>
    <td rowspan="2" >No Card (Prod. Order)</td>
    <td rowspan="2" >No. Lot (Prod. Demand)</td>
    <td rowspan="2" >Knitt</td>
    <td rowspan="2" >Demand Knitt (LOT Balance)</td>
    <td rowspan="2" >Project Awal</td>
	<td rowspan="2" >Project Akhir</td>  
     </tr>
  <tr align="center">
    <td >1</td>
    <td >2</td>
    <td >3</td>
    <td >4</td>
  </tr>
    <?php 
  $sqlDB21 = " SELECT 
	 
	STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	STOCKTRANSACTION.PROJECTCODE,
	CASE WHEN STOCKTRANSACTION.PROJECTCODE <> '' THEN STOCKTRANSACTION.PROJECTCODE ELSE ITXVIEWKNTORDER.ORIGDLVSALORDLINESALORDERCODE  END  AS PROJECT,
	COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_DUS,
	SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
	ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE,
	ITXVIEWKNTORDER.LEGALNAME1,
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
	ITXVIEWKK.WARNA,
	ITXVIEWKK.SUBCODE01, 
	ITXVIEWKK.SUBCODE02,
	ITXVIEWKK.SUBCODE03,
	ITXVIEWKK.SUBCODE04,
	ITXVIEWKK.SUBCODE05,
	ITXVIEWKK.SUBCODE06,
	ITXVIEWKK.SUBCODE07,
	ITXVIEWKK.SUBCODE08
	FROM DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION LEFT OUTER JOIN
	(SELECT 
	ITXVIEWKNTORDER.PRODUCTIONORDERCODE,	
	ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE,
	LISTAGG(DISTINCT  TRIM(ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE),', ') AS PRODUCTIONDEMANDCODE,
	ITXVIEWKNTORDER.LEGALNAME1 FROM 
DB2ADMIN.ITXVIEWKNTORDER
GROUP BY ITXVIEWKNTORDER.PRODUCTIONORDERCODE,
ITXVIEWKNTORDER.LEGALNAME1,
ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE) ITXVIEWKNTORDER
	 ON ITXVIEWKNTORDER.PRODUCTIONORDERCODE =STOCKTRANSACTION.ORDERCODE AND 
	 ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE=STOCKTRANSACTION.TRANSACTIONDATE
	LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
    STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
    LEFT OUTER JOIN ( SELECT i.WARNA, pr.LONGDESCRIPTION AS JNSKAIN,pd.PROJECTCODE,p.PRODUCTIONORDERCODE,pd.SUBCODE01,pd.SUBCODE02,pd.SUBCODE03,
	pd.SUBCODE04,pd.SUBCODE05,pd.SUBCODE06,pd.SUBCODE07,pd.SUBCODE08  FROM PRODUCTIONDEMANDSTEP p
	LEFT OUTER JOIN PRODUCTIONDEMAND pd ON pd.CODE =p.PRODUCTIONDEMANDCODE
	LEFT JOIN PRODUCT pr ON
    pr.ITEMTYPECODE = pd.ITEMTYPEAFICODE
    AND pr.SUBCODE01 = pd.SUBCODE01
    AND pr.SUBCODE02 = pd.SUBCODE02
    AND pr.SUBCODE03 = pd.SUBCODE03
    AND pr.SUBCODE04 = pd.SUBCODE04
    AND pr.SUBCODE05 = pd.SUBCODE05
    AND pr.SUBCODE06 = pd.SUBCODE06
    AND pr.SUBCODE07 = pd.SUBCODE07
    AND pr.SUBCODE08 = pd.SUBCODE08
    AND pr.SUBCODE09 = pd.SUBCODE09
    AND pr.SUBCODE10 = pd.SUBCODE10
    LEFT JOIN ITXVIEWCOLOR i ON
    pr.ITEMTYPECODE = pd.ITEMTYPEAFICODE
    AND i.SUBCODE01 = pd.SUBCODE01
    AND i.SUBCODE02 = pd.SUBCODE02
    AND i.SUBCODE03 = pd.SUBCODE03
    AND i.SUBCODE04 = pd.SUBCODE04
    AND i.SUBCODE05 = pd.SUBCODE05
    AND i.SUBCODE06 = pd.SUBCODE06
    AND i.SUBCODE07 = pd.SUBCODE07
    AND i.SUBCODE08 = pd.SUBCODE08
    AND i.SUBCODE09 = pd.SUBCODE09
    AND i.SUBCODE10 = pd.SUBCODE10
    GROUP BY pr.LONGDESCRIPTION,p.PRODUCTIONORDERCODE,pd.PROJECTCODE,pd.SUBCODE01,pd.SUBCODE02,pd.SUBCODE03,
	pd.SUBCODE04,pd.SUBCODE05,pd.SUBCODE06,pd.SUBCODE07,pd.SUBCODE08,i.WARNA) ITXVIEWKK ON ITXVIEWKK.PRODUCTIONORDERCODE =STOCKTRANSACTION.ORDERCODE AND 
    ITXVIEWKK.PROJECTCODE = STOCKTRANSACTION.PROJECTCODE
WHERE (STOCKTRANSACTION.ITEMTYPECODE ='KGF' OR STOCKTRANSACTION.ITEMTYPECODE ='FKG') and STOCKTRANSACTION.LOGICALWAREHOUSECODE ='M021' AND
STOCKTRANSACTION.ONHANDUPDATE > 1 AND TRANSACTIONDATE BETWEEN '$Awal' AND '$Akhir' AND NOT ORDERCODE IS NULL 
GROUP BY
STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	STOCKTRANSACTION.PROJECTCODE,
	ITXVIEWKNTORDER.ORIGDLVSALORDLINESALORDERCODE,
	ITXVIEWKNTORDER.LEGALNAME1,
	ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE,
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
	ITXVIEWKK.WARNA,
	ITXVIEWKK.SUBCODE01, 
	ITXVIEWKK.SUBCODE02,
	ITXVIEWKK.SUBCODE03,
	ITXVIEWKK.SUBCODE04,
	ITXVIEWKK.SUBCODE05,
	ITXVIEWKK.SUBCODE06,
	ITXVIEWKK.SUBCODE07,
	ITXVIEWKK.SUBCODE08
";
	$stmt1   = db2_exec($conn1,$sqlDB21, array('cursor'=>DB2_SCROLLABLE));
$no=1;				  
    while($rowdb21 = db2_fetch_assoc($stmt1)){ 
if ($rowdb21['LOGICALWAREHOUSECODE'] =='M501') { $knitt = 'LT2'; }
else if($rowdb21['LOGICALWAREHOUSECODE'] ='P501'){ $knitt = 'LT1'; }
$kdbenang=trim($rowdb21['DECOSUBCODE02'])." ".trim($rowdb21['DECOSUBCODE03']);
$sqlDB22 = " SELECT SALESORDER.CODE, SALESORDER.EXTERNALREFERENCE, SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
		ITXVIEWAKJ.LEGALNAME1, ITXVIEWAKJ.ORDERPARTNERBRANDCODE, ITXVIEWAKJ.LONGDESCRIPTION
		FROM DB2ADMIN.SALESORDER SALESORDER LEFT OUTER JOIN DB2ADMIN.ITXVIEWAKJ 
       	ITXVIEWAKJ ON SALESORDER.CODE=ITXVIEWAKJ.CODE
		WHERE SALESORDER.CODE='$rowdb21[PROJECTCODE]' ";
$stmt2   = db2_exec($conn1,$sqlDB22, array('cursor'=>DB2_SCROLLABLE));
$rowdb22 = db2_fetch_assoc($stmt2);
		
$sqlDB23 = " SELECT p.SUBCODE01,p.SUBCODE02,p.SUBCODE03,p.SUBCODE04,p.SUBCODE05,p.SUBCODE06,p.SUBCODE07, p.LONGDESCRIPTION FROM (
SELECT p2.ITEMTYPEAFICODE,p2.SUBCODE01,p2.SUBCODE02,p2.SUBCODE03,p2.SUBCODE04,
p2.SUBCODE05,p2.SUBCODE06,p2.SUBCODE07  FROM PRODUCTIONDEMAND p 
LEFT OUTER JOIN PRODUCTIONRESERVATION p2 ON p.CODE =p2.ORDERCODE 
WHERE p.ITEMTYPEAFICODE ='KGF' AND p.SUBCODE01='".trim($rowdb21['DECOSUBCODE01'])."' 
AND p.SUBCODE02 ='".trim($rowdb21['DECOSUBCODE02'])."' AND p.SUBCODE03 ='".trim($rowdb21['DECOSUBCODE03'])."' AND
p.SUBCODE04='".trim($rowdb21['DECOSUBCODE04'])."' AND p.PROJECTCODE ='".trim($rowdb21['PROJECTCODE'])."'
) a LEFT OUTER JOIN PRODUCT p ON
p.ITEMTYPECODE ='GYR' AND
p.SUBCODE01= a.SUBCODE01 AND p.SUBCODE02= a.SUBCODE02 AND 
p.SUBCODE03= a.SUBCODE03 AND p.SUBCODE04= a.SUBCODE04 AND 
p.SUBCODE05= a.SUBCODE05 AND p.SUBCODE06= a.SUBCODE06 AND
p.SUBCODE07= a.SUBCODE07 
GROUP BY 
p.SUBCODE01,p.SUBCODE02, 
p.SUBCODE03,p.SUBCODE04,
p.SUBCODE05,p.SUBCODE06,
p.SUBCODE07,p.LONGDESCRIPTION ";
$stmt3   = db2_exec($conn1,$sqlDB23, array('cursor'=>DB2_SCROLLABLE));
$ai=0;
while($rowdb23 = db2_fetch_assoc($stmt3)){
	$a[$ai]=$rowdb23['LONGDESCRIPTION'];
	$ai++;
}
$sqlDB24 = " SELECT pr.LONGDESCRIPTION,p.PRODUCTIONORDERCODE,pd.SUBCODE01,pd.SUBCODE02,pd.SUBCODE03,
	pd.SUBCODE04,pd.SUBCODE05,pd.SUBCODE06,pd.SUBCODE07,pd.SUBCODE08,pd.INTERNALREFERENCE,
	LISTAGG(DISTINCT  TRIM(pd.CODE),', ') AS PRODUCTIONDEMANDCODE
	FROM PRODUCTIONDEMANDSTEP p
	LEFT OUTER JOIN PRODUCTIONDEMAND pd ON pd.CODE =p.PRODUCTIONDEMANDCODE
	LEFT JOIN PRODUCT pr ON
    pr.ITEMTYPECODE = pd.ITEMTYPEAFICODE
    AND pr.SUBCODE01 = pd.SUBCODE01
    AND pr.SUBCODE02 = pd.SUBCODE02
    AND pr.SUBCODE03 = pd.SUBCODE03
    AND pr.SUBCODE04 = pd.SUBCODE04
    AND pr.SUBCODE05 = pd.SUBCODE05
    AND pr.SUBCODE06 = pd.SUBCODE06
    AND pr.SUBCODE07 = pd.SUBCODE07
    AND pr.SUBCODE08 = pd.SUBCODE08
    AND pr.SUBCODE09 = pd.SUBCODE09
    AND pr.SUBCODE10 = pd.SUBCODE10
WHERE pd.PROJECTCODE ='$rowdb21[PROJECTCODE]' AND p.PRODUCTIONORDERCODE='$rowdb21[ORDERCODE]'	
	GROUP BY pr.LONGDESCRIPTION,p.PRODUCTIONORDERCODE,pd.SUBCODE01,pd.SUBCODE02,pd.SUBCODE03,
	pd.SUBCODE04,pd.SUBCODE05,pd.SUBCODE06,pd.SUBCODE07,pd.SUBCODE08,pd.INTERNALREFERENCE ";
$stmt4   = db2_exec($conn1,$sqlDB24, array('cursor'=>DB2_SCROLLABLE));
$rowdb24 = db2_fetch_assoc($stmt4);
		
	if($rowdb22['LEGALNAME1']==""){$langganan="";}else{$langganan=$rowdb22['LEGALNAME1'];}
	if($rowdb22['ORDERPARTNERBRANDCODE']==""){$buyer="";}else{$buyer=$rowdb22['ORDERPARTNERBRANDCODE'];}
	$knitt1="ITTI";	
	 echo"
	 
	 <tr >
	 <td >$no</td>
	 <td >".$rowdb21['TRANSACTIONDATE']."</td>
	 <td >$langganan</td>	 
	 <td >".$a[0]."</td> 
	 <td >".$a[1]."</td> 
	 <td >".$a[2]."</td> 
	 <td >".$a[3]."</td> 
	 <td >".$kdbenang."</td>
	 <td >".$rowdb21['DECOSUBCODE04']."</td>
	 <td align=right>".$rowdb21['QTY_DUS']."</td>
	 <td align=right>".number_format($rowdb21['QTY_KG'],'2','.',',')."</td>	
	 <td >".$rowdb21['WARNA']."</td>
	 <td >'".$rowdb21['ORDERCODE']."</td> 
	 <td >'".$rowdb24['PRODUCTIONDEMANDCODE']."</td> 
	 <td >$knitt1</td>
	 <td >'".$rowdb21['LOTCODE']."</td>
	 <td >".$rowdb24['INTERNALREFERENCE']."</td>
	 <td >".$rowdb21['PROJECTCODE']."</td>
	 </tr>
	 ";
	 $no++;
	 $totqt=$totqt+$rowdb21['QTY_KG'];
	 $totr=$totr+$rowdb21['QTY_DUS'];	
	 }
  ?>
  <tr align="right">
  	<td colspan="10"  ><b>Total</b></td>
  	<td > <b><?php echo number_format($totr,'2','.',','); ?></b></td>
    <td > <b><?php echo number_format($totqt,'2','.',','); ?></b></td>
	<td colspan="6" >&nbsp;</td>
	</tr>
</table>


        


